### ISSUE TITLE
Where to copy the repo content?

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/proto2cpp#4]
![capture](https://user-images.githubusercontent.com/40594242/42620068-32655bec-85ba-11e8-8219-e6de805b0f56.JPG)
i think i have not correctly copied the content of the repo. can you explain what does the "desired path to proto2cpp.py" means? i dont understand it i tried copying it in CMakeLists.txt folderbut it doesnt work. need help!!!

**Comment by ghost** [comment]
You can copy it at any place you like. You just have to give the right path in the configuration. You can place it in the directory of the OSI source files for example?

**Comment by mshaheerm** [comment]
ok i did it. and it works ok i guess but i dont know what should be the output? what would be generated? what should i do next? the osi visualizer or what? thankyou anyways for your answer :)
