### ISSUE TITLE
doxygen bug

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/proto2cpp#6]
Large proto documentations may lead to some unexpected '*' or previous '///' in the html documentation.

**Comment by jdsika** [comment]
@vkresch is this still an issue?

**Comment by vkresch** [comment]
@carsten-kuebler can you provide a link on which specific html page you saw this behaviour?

**Comment by vkresch** [comment]
For now I will close it since I can't see or reproduce the bug.
